
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress, Contract, ContractBase, ContractFunctionInteraction, ContractMethod, DeployMethod, EthAddress, FieldLike, AztecAddressLike, EthAddressLike, Wallet } from '@aztec/aztec.js';
import { Fr, Point } from '@aztec/foundation/fields';
import { PXE, PublicKey } from '@aztec/types';
import { ContractAbi } from '@aztec/foundation/abi';
import TraderContractAbiJson from '../../target/trader/Trader.json' assert { type: 'json' };
export const TraderContractAbi = TraderContractAbiJson as ContractAbi;

/**
 * Type-safe interface for contract Trader;
 */
export class TraderContract extends ContractBase {
  
  private constructor(
    completeAddress: CompleteAddress,
    wallet: Wallet,
    portalContract = EthAddress.ZERO
  ) {
    super(completeAddress, TraderContractAbi, wallet, portalContract);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, TraderContract.abi, wallet) as Promise<TraderContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(pxe: PXE, token0: FieldLike, token1: FieldLike) {
    return new DeployMethod<TraderContract>(Point.ZERO, pxe, TraderContractAbi, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public key to derive the address.
   */
  public static deployWithPublicKey(pxe: PXE, publicKey: PublicKey, token0: FieldLike, token1: FieldLike) {
    return new DeployMethod<TraderContract>(publicKey, pxe, TraderContractAbi, Array.from(arguments).slice(2));
  }
  

  
  /**
   * Returns this contract's ABI.
   */
  public static get abi(): ContractAbi {
    return TraderContractAbi;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public methods!: {
    
    /** trade_token0(token0_from: struct, amount_token0: field, amount_token1: field, nonce: field, nonce_transfer_token0: field, nonce_transfer_token1: field) */
    trade_token0: ((token0_from: AztecAddressLike, amount_token0: FieldLike, amount_token1: FieldLike, nonce: FieldLike, nonce_transfer_token0: FieldLike, nonce_transfer_token1: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
